openapi: 3.0.0
info:
  title: SmartAPI-CAMARA R2.0.0 - Tests
  description: >-
    Comprehensive Postman collection for all CAMARA APIs including Device Identifier, Number Verification, SIM Swap,
    Device Reachability Status, Location Retrieval, Location Verification, and Device Roaming Status
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: From Postman base_url
paths:
  /v1/bc-authorize:
    post:
      summary: v1/bc-authorize
      operationId: Location_Verification_-_v3_v1bc-authorize
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /v1/token:
    post:
      summary: v1/token
      operationId: Location_Verification_-_v3_v1token
      parameters:
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /camara-sandbox/sim-swap/v1/retrieve-date:
    post:
      summary: SIM Swap / Retrieve SIM Swap Date - RETRIEVE_DATE - Smart2M
      operationId: SIM_Swap_-_v1_SIM_Swap__Retrieve_SIM_Swap_Date_-_RETRIEVE_DATE_-_Smart2M
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example: {}
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /sim-swap/v1/retrieve-date:
    post:
      summary: SIM Swap / Retrieve SIM Swap Date - GENERIC_429_TOO_MANY_REQUESTS - N/A
      operationId: SIM_Swap_-_v1_-_Negative_SIM_Swap__Retrieve_SIM_Swap_Date_-_GENERIC_429_TOO_MANY_REQUESTS_-_NA
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              phoneNumber: '+346661113334'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /sim-swap/v1/check:
    post:
      summary: SIM Swap / Check SIM Swap - GENERIC_429_TOO_MANY_REQUESTS
      operationId: SIM_Swap_-_v1_-_Negative_SIM_Swap__Check_SIM_Swap_-_GENERIC_429_TOO_MANY_REQUESTS
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              phoneNumber: +{{phoneNumber}}
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /camara-sandbox/sim-swap/v2/retrieve-date:
    post:
      summary: SIM Swap / Retrieve SIM Swap Date - RETRIEVE_DATE - Smart2M
      operationId: SIM_Swap_-_v21_SIM_Swap__Retrieve_SIM_Swap_Date_-_RETRIEVE_DATE_-_Smart2M
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example: {}
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /sim-swap/v2/retrieve-date:
    post:
      summary: SIM Swap / Retrieve SIM Swap Date - GENERIC_429_TOO_MANY_REQUESTS - N/A
      operationId: SIM_Swap_-_v21_-_Negative_SIM_Swap__Retrieve_SIM_Swap_Date_-_GENERIC_429_TOO_MANY_REQUESTS_-_NA
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              phoneNumber: '+346661113334'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /sim-swap/v2/check:
    post:
      summary: SIM Swap / Check SIM Swap - GENERIC_429_TOO_MANY_REQUESTS
      operationId: SIM_Swap_-_v21_-_Negative_SIM_Swap__Check_SIM_Swap_-_GENERIC_429_TOO_MANY_REQUESTS
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              phoneNumber: +{{phoneNumber}}
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /location-retrieval/v0.3/retrieve:
    post:
      summary: Location Retrieval / Retrieve Device Location - Unable to locate device
      operationId: Location_Retrieval_-_v03_Location_Retrieval__Retrieve_Device_Location_-_Unable_to_locate_device
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              device:
                phoneNumber: '+123456789'
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /retrieve:
    post:
      summary: Location Retrieval / Retrieve Device Location - GENERIC_401_UNAUTHENTICATED
      operationId: Location_Retrieval_-_v05_Location_Retrieval__Retrieve_Device_Location_-_GENERIC_401_UNAUTHENTICATED
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              device:
                phoneNumber: '+123456789'
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /location-retrieval/v0.5/retrieve:
    post:
      summary: Location Retrieval / Retrieve Device Location - Unable to locate device
      operationId: Location_Retrieval_-_v05_Location_Retrieval__Retrieve_Device_Location_-_Unable_to_locate_device
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              device:
                phoneNumber: '+123456789'
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /location-verification/v1/verify:
    post:
      summary: Location Verification / Verify Device Location - Unable to locate device
      operationId: Location_Verification_-_v1_Location_Verification__Verify_Device_Location_-_Unable_to_locate_device
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              device:
                phoneNumber: '+123456789'
              area:
                areaType: CIRCLE
                center:
                  latitude: 50.735851
                  longitude: 7.10066
                radius: 50000
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
  /location-verification/v3/verify:
    post:
      summary: Location Verification / Verify Device Location - Unable to locate device
      operationId: Location_Verification_-_v3_Location_Verification__Verify_Device_Location_-_Unable_to_locate_device
      parameters:
        - name: x-correlator
          in: header
          required: false
          schema:
            type: string
          description: Correlation id for the different services
        - name: Accept
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body (from Postman)
            example:
              device:
                phoneNumber: '+123456789'
              area:
                areaType: CIRCLE
                center:
                  latitude: 50.735851
                  longitude: 7.10066
                radius: 50000
              maxAge: 120
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer token
security:
  - BearerAuth: []
